export const CARDS = [
  { id: 'c1',  front: '15 says ___ / 5 and 2 say ___', back: '15 says IF · 5 and 2 say WHEN and WHERE.' },
  { id: 'c2',  front: 'Where does the stop go?', back: 'Below the FIRST dip — a few ticks LOWER than the crowd.' },
  { id: 'c3',  front: 'T1 = ?', back: 'T1 = 1R. The instant T1 fills → move stop to BREAKEVEN.' },
  { id: 'c4',  front: 'T2 = ?', back: 'T2 = 2R. The middle pair takes the meat.' },
  { id: 'c5',  front: 'Runner trails what?', back: 'The 9 EMA. The 9 is not a separate strategy.' },
  { id: 'c6',  front: 'What is the candle\'s job?', back: 'Grade the entry — GO/NO-GO and conviction cue. NOT a size dial.' },
  { id: 'c7',  front: 'When the 15-min is sideways?', back: 'Sit out. That IS the trade.' },
  { id: 'c8',  front: 'Patterns we NEVER trade?', back: 'Reversals (DT/DB, H&S, wedges, V), bilateral ranges/triangles, and standalone candles.' },
  { id: 'c9',  front: 'Why the SECOND dip, not the first?', back: 'The first rally fails at the neckline — never closes above. That failure IS the bait; there was no entry to skip. After Dip 2 (a higher low), the FIRST close above the neckline is the entry. Same pattern for shorts, mirrored.' },
  { id: 'c10', front: 'When do you enter?', back: 'The FIRST 2-min candle that CLOSES above the neckline (long) or below it (short). No retest. No second close needed. The first close is the contract.' },
  { id: 'c11', front: '20 EMA\'s job?', back: 'Health filter. A healthy pullback holds near/above it.' },
  { id: 'c12', front: 'How many contracts? When do you change size?', back: 'Fixed 6. Same size every trade. No conviction sizing yet.' },
  { id: 'c13', front: 'Add to a winner?', back: 'No. No pyramiding yet. A fresh, separate valid setup is a NEW trade.' },
  { id: 'c14', front: 'Circuit breaker — when does the day end?', back: 'When max trades OR max loss per session is hit. Done.' },
  { id: 'c15', front: 'Going live criteria?', back: 'Net green in sim + every trade followed the 7-step checklist. Start at 1 micro. Scale slowly.' },
  { id: 'c16', front: 'Grade yourself on…', back: 'Following the plan. NOT on winning.' },
  { id: 'c17', front: 'Why was the old strategy bleeding?', back: 'Counter-trend reversals + stop in FRONT of the crowd (got hunted).' },
  { id: 'c18', front: 'Mantra for sizing & emotion?', back: 'Same size every trade. The discretion is in WHETHER, not how much.' },
]
