export const CARDS = [
  { id: 'c1',  front: '15 says ___ / 5 and 2 say ___', back: '15 says IF · 5 and 2 say WHEN and WHERE. And between them stands the Gatekeeper: LOCATION decides "now, or not now."' },
  { id: 'c2',  front: 'Where does the stop go?', back: 'Two steps. TENTATIVE: 4-6 ticks beyond the broken trendline (the trendline level itself at the break — NOT below the breakout candle\'s close). FINAL: just past the STRUCTURE — the swing low at the bottom of the bull-flag pullback (longs), or the swing high at the top of the bear-flag bounce (shorts). Anchor the final stop to the structure.' },
  { id: 'c3',  front: 'T1 = ?', back: 'T1 = 1R. The instant T1 fills → trail the stop to 4–6 ticks behind the newest 2-min swing (only if tighter — never at entry). Then ratchet behind every new swing. The stop only ever tightens.' },
  { id: 'c4',  front: 'T2 = ?', back: 'T2 = 2R. The middle pair takes the meat.' },
  { id: 'c5',  front: 'Runner trails what?', back: 'The 9 EMA. The 9 is not a separate strategy.' },
  { id: 'c6',  front: 'What is the candle\'s job?', back: 'Grade the entry — GO/NO-GO and conviction cue. NOT a size dial.' },
  { id: 'c7',  front: 'When the 15-min is sideways?', back: 'Sit out. That IS the trade.' },
  { id: 'c8',  front: 'Patterns we NEVER trade?', back: 'Reversals (DT/DB, H&S, wedges, V), bilateral ranges/triangles, and standalone candles.' },
  { id: 'c9',  front: 'When does the pullback give you a trade?', back: 'Only when the 2-min CLOSES through the trendline. The pullback (long) or bounce (short) forming is not an entry on its own — no matter how clean the shape looks. Wait for the close above the descending trendline (long) or below the ascending trendline (short). That close is the only trigger.' },
  { id: 'c10', front: 'When do you enter?', back: 'Only with the Gatekeeper OPEN in your direction — then the FIRST 2-min candle that CLOSES above the 2-min DESCENDING TRENDLINE (longs) — the diagonal connecting the lower highs of the pullback — or BELOW the 2-min ASCENDING TRENDLINE (shorts) — the diagonal connecting the higher lows of the bounce. Enter all 6 contracts at the open of the next candle.' },
  { id: 'c11', front: '20 EMA\'s job?', back: 'Health filter. A healthy pullback holds near/above it.' },
  { id: 'c12', front: 'How many contracts? When do you change size?', back: 'Fixed 6. Same size every trade. No conviction sizing yet.' },
  { id: 'c13', front: 'Add to a winner?', back: 'No. No pyramiding yet. A fresh, separate valid setup is a NEW trade.' },
  { id: 'c14', front: 'Circuit breaker — when does the day end?', back: 'When max trades OR max loss per session is hit. Done.' },
  { id: 'c15', front: 'Going live criteria?', back: 'Net green in sim + every trade followed the 7-step checklist. Start at 1 micro. Scale slowly.' },
  { id: 'c16', front: 'Grade yourself on…', back: 'Following the plan. NOT on winning.' },
  { id: 'c17', front: 'Why was the old strategy bleeding?', back: 'Counter-trend reversals + stop in FRONT of the crowd (got hunted).' },
  { id: 'c18', front: 'Mantra for sizing & emotion?', back: 'Same size every trade. The discretion is in WHETHER, not how much.' },
  { id: 'c19', front: 'The upgraded sequence?', back: 'TREND → LOCATION → PATTERN → TRIGGER. Trend (15/5) grants directional permission only; Location (the Gatekeeper) decides now-or-not-now; Pattern = flags only; Trigger = the 2-min trendline close. All four must agree.' },
  { id: 'c20', front: 'The LONG GATE — recite it', back: 'On the 2-min, ALL required: price above VWAP · above the 9 EMA · above the 20 EMA with the 20 rising · above the 200 EMA. A+ when fully stacked (9 > 20 > 200, VWAP below price). Any single miss = gate closed = no long.' },
  { id: 'c21', front: 'The SHORT GATE?', back: 'Exact mirror: 15/5 LH/LL; price below VWAP, below the 9, below the 20 with the 20 falling, below the 200. A+ stacked 9 < 20 < 200.' },
  { id: 'c22', front: '15/5 bullish but the 2-min is below VWAP and the 200 — your move?', back: 'FLAT. No long (gate closed). No short (that\'s shorting a pullback inside an uptrend). Three positions exist: long, short, and flat. FLAT IS A POSITION.' },
  { id: 'c23', front: 'What is a trap flag?', back: 'A flag on the wrong side of the stack — a "bull flag" below VWAP/9/20/200 is the same shape with opposite context; from the other side it\'s often the bear flag. Flag quality: touching the 9/20 is healthy, but a 2-min CLOSE below the 20 — or below VWAP — kills a bull flag. Mirror for bear flags.' },
  { id: 'c24', front: 'The Reclaim Sequence?', back: '1) Decisive 2-min CLOSE above BOTH VWAP and the 200. 2) HOLD — price retests them and holds from above. 3) The FIRST flag after the held reclaim is valid — often the best trade of the move. Mirror for shorts. Never anticipate it.' },
  { id: 'c25', front: 'The Runway Rule?', back: 'No wall — VWAP or the 200 EMA — may sit between the entry and the first scale-out target. Wall in the way = skip the trade.' },
  { id: 'c26', front: 'Chop tells — name them', back: 'Any ONE = sit on your hands: 9/20 flat and braided · flat VWAP · price crossing VWAP repeatedly (~30 min) · the squeeze (price sandwiched between 9/20 and VWAP/200) · failed breakouts both ways with small overlapping candles.' },
]
