// 18 scenarios for the "Trade or Skip" trainer.
// Each scenario: id, expected ('LONG'|'SHORT'|'SKIP'|'WAIT'), trap (boolean — was this a classic trap to avoid?),
// ctx (15-min context label), ctxColor, candle, values (y-array 0..100), trigger, dip1Idx, dip2Idx, entryIdx (optional),
// stopY (optional), why (teaching), title.

export const SCENARIOS = [
  {
    id: 's1',
    expected: 'LONG',
    trap: false,
    title: 'Textbook with-trend long',
    ctx: '15-min: higher highs & higher lows',
    ctxColor: 'emerald',
    candle: 'engulfing',
    values: [18, 34, 52, 43, 53, 46, 60, 72],
    triggerY: 53,
    dip1Idx: 3,
    dip2Idx: 5,
    entryIdx: 6,
    stopY: 37,
    why: 'Textbook with-trend bull flag. The 5-min pullback is making lower highs while holding above the prior swing low — clean pullback. The TRIGGER is the FIRST 2-min candle that CLOSES above the descending 2-min trendline (the diagonal connecting those lower highs). Take it. Stop: tentative 4-6 ticks beyond the broken trendline, final at the structure (the swing low at the bottom of the pullback).',
  },
  {
    id: 's2',
    expected: 'SHORT',
    trap: false,
    title: 'Mirror — with-trend short',
    ctx: '15-min: lower highs & lower lows',
    ctxColor: 'coral',
    candle: 'bearish engulfing',
    values: [82, 66, 48, 57, 47, 54, 40, 28],
    triggerY: 47,
    dip1Idx: 3,
    dip2Idx: 5,
    entryIdx: 6,
    stopY: 63,
    stopLabel: 'Stop (above bounce swing high)',
    why: 'With-trend BEAR FLAG. 15-min must be in downtrend (lower highs and lower lows — MANDATORY for shorts). The 5-min bounce is making higher lows while holding below the prior swing high — clean bounce against the downtrend. TRIGGER: FIRST 2-min candle that CLOSES BELOW the ascending 2-min trendline (the diagonal connecting those higher lows). Stop: tentative 4-6 ticks above the broken trendline, final at the structure (swing high at the top of the bounce). Bear flags work fast — time stop is 2 candles (4 minutes), not 3.',
  },
  {
    id: 's3',
    expected: 'SKIP',
    trap: true,
    title: 'Counter-trend long attempt in a downtrend',
    ctx: '15-min: DOWNTREND (lower highs & lower lows)',
    ctxColor: 'coral',
    candle: 'doji',
    values: [70, 55, 42, 40, 44, 41, 50, 58],
    triggerY: 44,
    dip1Idx: 3,
    dip2Idx: 5,
    why: 'Trying to buy inside a 15-min downtrend — a counter-trend long against the trend. The candle may look beautiful but the context is wrong. No bottom-picking. Sit out.',
  },
  {
    id: 's4',
    expected: 'SKIP',
    trap: true,
    title: 'Sideways tape',
    ctx: '15-min: sideways / choppy, no clear trend',
    ctxColor: 'muted',
    candle: 'mixed',
    values: [50, 44, 55, 46, 54, 45, 53, 47],
    why: 'No trend, no permission. The 15-min gate is closed. Sitting out IS the trade.',
  },
  {
    id: 's5',
    expected: 'WAIT',
    trap: false,
    title: 'Pullback forming — no trendline close yet',
    ctx: '15-min: higher highs & higher lows',
    ctxColor: 'emerald',
    candle: 'forming',
    values: [20, 38, 55, 45, 55, 50, 52, 53],
    triggerY: 55,
    dip1Idx: 3,
    why: 'The pullback is forming and making lower highs against the descending trendline, but no 2-min candle has closed above the trendline yet — the trendline close is the only trigger. Wait. There is no entry until the 2-min candle CLOSES above the trendline. Patience IS the edge.',
  },
  {
    id: 's6',
    expected: 'SKIP',
    trap: true,
    title: 'Unhealthy knife pullback',
    ctx: '15-min: higher highs & higher lows',
    ctxColor: 'emerald',
    candle: 'doji',
    values: [30, 48, 60, 40, 30, 25, 28, 33],
    ema20: [28, 35, 44, 46, 44, 40, 36, 34],
    why: 'The pullback knifed well below the 20 EMA and stayed there. Healthy pullbacks don\'t cave like this. Character has changed. Skip.',
  },
  {
    id: 's7',
    expected: 'SKIP',
    trap: true,
    title: 'Lower high on the 15-min',
    ctx: '15-min: just printed a LOWER HIGH',
    ctxColor: 'coral',
    candle: 'engulfing',
    values: [40, 55, 68, 60, 52, 57, 49, 46],
    triggerY: 57,
    dip1Idx: 4,
    dip2Idx: 5,
    why: 'The 15-min uptrend is now in question — the hard gate fails. Even with a "perfect" 2-min picture, no long.',
  },
  {
    id: 's8',
    expected: 'SKIP',
    trap: false,
    title: 'No candle confirmation',
    ctx: '15-min: higher highs & higher lows',
    ctxColor: 'emerald',
    candle: 'weak doji',
    values: [22, 36, 52, 44, 52, 46, 55, 61],
    triggerY: 52,
    dip1Idx: 3,
    dip2Idx: 5,
    entryIdx: 6,
    stopY: 38,
    why: 'Valid pullback structure and a trendline close, but no confirmation candle — just a weak doji. Lowest conviction. Smaller size or skip. Best practice: skip until the candle agrees.',
  },

  // ─── Phase 8 additions ─────────────────────────────────────────────
  {
    id: 's9',
    expected: 'LONG',
    trap: false,
    title: 'Clean with-trend bull-flag entry',
    ctx: '15-min: higher highs & higher lows',
    ctxColor: 'emerald',
    candle: 'engulfing',
    values: [25, 40, 58, 48, 58, 50, 63, 74],
    triggerY: 58,
    dip1Idx: 3,
    dip2Idx: 5,
    entryIdx: 6,
    stopY: 42,
    why: 'Clean with-trend bull flag. Pullback making lower highs, holding above the prior swing low, riding the rising 20 EMA → FIRST 2-min close above the descending 2-min trendline. Take it.',
  },
  {
    id: 's10',
    expected: 'SKIP',
    trap: true,
    title: 'Climactic 5th push + deep pullback',
    ctx: '15-min HH/HL but 5th extended push, climactic',
    ctxColor: 'gold',
    candle: 'climactic',
    values: [40, 55, 72, 60, 78, 55, 70, 52],
    why: 'A blow-off bar followed by a deep pullback is exhaustion. The trend may be ending. Stop taking new longs.',
  },
  {
    id: 's11',
    expected: 'SHORT',
    trap: false,
    title: 'With-trend bear-flag entry',
    ctx: '15-min: lower highs & lower lows',
    ctxColor: 'coral',
    candle: 'bearish engulfing',
    values: [78, 62, 45, 55, 45, 52, 38, 27],
    triggerY: 45,
    dip1Idx: 3,
    dip2Idx: 5,
    entryIdx: 6,
    stopY: 60,
    stopLabel: 'Stop (above bounce swing high)',
    why: 'With-trend bear flag. 15-min downtrend (mandatory). The 5-min bounce is making higher lows while holding below the prior swing high → FIRST 2-min close BELOW the ascending 2-min trendline (the diagonal connecting those higher lows). Stop: tentative 4-6 ticks above the broken trendline, final at the structure (swing high at the top of the bounce). Time stop: 2 candles.',
  },
  {
    id: 's12',
    expected: 'SKIP',
    trap: true,
    title: '5-min broke its prior swing low',
    ctx: '15-min HH/HL, but the 5-min broke its prior swing low',
    ctxColor: 'coral',
    candle: 'doji',
    values: [30, 46, 60, 44, 30, 33, 29, 35],
    why: 'The 5-min health failed — the pullback broke the prior swing low. The "WHERE" gate is closed. Stand aside.',
  },
  {
    id: 's13',
    expected: 'WAIT',
    trap: false,
    title: 'No 2-min trendline CLOSE yet',
    ctx: '15-min: higher highs & higher lows',
    ctxColor: 'emerald',
    candle: 'forming',
    values: [22, 38, 55, 45, 55, 47, 52, 52],
    triggerY: 55,
    dip1Idx: 3,
    dip2Idx: 5,
    why: 'The pullback is well-formed against the descending trendline, but the 2-min hasn\'t printed the FIRST close above the trendline yet. The trendline close is the only trigger. Wait. The trendline close is the contract.',
  },
  {
    id: 's14',
    expected: 'SKIP',
    trap: true,
    title: 'Counter-trend short attempt in an uptrend',
    ctx: '15-min: higher highs & higher lows',
    ctxColor: 'emerald',
    candle: 'rejection',
    values: [40, 58, 72, 64, 72, 66, 60, 55],
    why: 'A pullback shape tempting a short — but the 15-min trend is UP. Shorting an uptrend is counter-trend. With-trend only. Never short this.',
  },
  {
    id: 's15',
    expected: 'LONG',
    trap: false,
    title: 'Strong trend, shallow pullback',
    ctx: '15-min: strong HH/HL',
    ctxColor: 'emerald',
    candle: 'engulfing',
    values: [30, 48, 62, 57, 63, 58, 68, 78],
    ema20: [28, 36, 46, 50, 52, 54, 60, 66],
    triggerY: 63,
    dip1Idx: 3,
    dip2Idx: 5,
    entryIdx: 6,
    stopY: 53,
    why: 'Strong trend, shallow pullback riding the 9 EMA — textbook A+ bull-flag entry on the trendline close. Take it.',
  },
  {
    id: 's16',
    expected: 'SKIP',
    trap: true,
    title: 'Sideways range',
    ctx: '15-min: sideways range, no trend',
    ctxColor: 'muted',
    candle: 'doji',
    values: [48, 42, 54, 43, 53, 44, 53, 45],
    why: 'Clean bounces, but no trend. We don\'t trade ranges. Sit out.',
  },
  {
    id: 's17',
    expected: 'LONG',
    trap: false,
    title: 'Morning star at the trendline close (Strong, not A+)',
    ctx: '15-min: higher highs & higher lows',
    ctxColor: 'emerald',
    candle: 'morning star',
    values: [24, 40, 56, 46, 56, 48, 60, 70],
    triggerY: 56,
    dip1Idx: 3,
    dip2Idx: 5,
    entryIdx: 6,
    stopY: 41,
    why: 'Valid with-trend bull-flag entry confirmed by a morning star at the trendline close — a Strong (not A+) candle. Rare when you get it. Take it.',
  },
  {
    id: 's18',
    expected: 'SKIP',
    trap: true,
    title: 'Don\'t chase — no pullback',
    ctx: '15-min HH/HL, but price far above the 20 EMA with no pullback',
    ctxColor: 'emerald',
    candle: 'thrust',
    values: [20, 35, 52, 66, 78, 84, 80, 86],
    ema20: [18, 24, 32, 42, 52, 60, 64, 68],
    why: 'Nothing to buy. Don\'t chase. Wait for a pullback.',
  },

  // ─── The Gatekeeper drills (D1–D6) — VWAP + EMA location filter ───────────
  {
    id: 's19',
    expected: 'SKIP',
    trap: true,
    title: 'D1 · Bullish structure, bearish location',
    ctx: '15-min & 5-min: HH/HL — but check the 2-min LOCATION',
    ctxColor: 'gold',
    candle: 'doji',
    values: [44, 38, 30, 25, 29, 26, 31, 28],
    ema9: [46, 41, 35, 31, 32, 30, 33, 31],
    ema20: [50, 46, 41, 38, 37, 36, 36, 35],
    vwap: [58, 56, 54, 52, 51, 50, 49, 48],
    ema200: [62, 62, 61, 61, 60, 60, 59, 59],
    why: 'FLAT. The 15 and 5 print higher highs and higher lows, but the 2-min trades below VWAP, the 9, the 20 AND the 200 — sellers own right now. The Gatekeeper is closed: no long. And no short either — that would be shorting a pullback inside an uptrend, the mirror image of the original mistake. Three positions exist: long, short, and flat. Flat is a position.',
  },
  {
    id: 's20',
    expected: 'SKIP',
    trap: true,
    title: 'D2 · Reclaim incomplete',
    ctx: '2-min back above the 9 & 20 — still below VWAP and the 200',
    ctxColor: 'gold',
    candle: 'forming',
    values: [40, 34, 28, 25, 30, 34, 37, 36],
    ema9: [42, 37, 32, 28, 29, 31, 33, 34],
    ema20: [46, 42, 38, 34, 33, 33, 33, 34],
    vwap: [55, 53, 51, 50, 49, 48, 47, 47],
    ema200: [60, 60, 59, 59, 58, 58, 57, 57],
    why: 'FLAT. Reclaiming the 9 and 20 is step zero — the Reclaim Sequence needs 1) a decisive 2-min close above BOTH VWAP and the 200, then 2) a HOLD from above, before 3) the first flag is valid. If you said WAIT with your eyes on the Reclaim Sequence, the spirit is right — but until that decisive close prints there is no setup forming at all, and anticipating a reclaim is on the never-trade list. You are flat.',
  },
  {
    id: 's21',
    expected: 'SKIP',
    trap: true,
    title: 'D3 · The squeeze — walls overhead',
    ctx: '2-min above the 9/20 but below VWAP & the 200 — the squeeze',
    ctxColor: 'gold',
    candle: 'small overlapping',
    values: [30, 34, 32, 36, 35, 38, 36, 39],
    ema9: [29, 31, 32, 33, 34, 35, 35, 36],
    ema20: [27, 29, 30, 31, 32, 33, 33, 34],
    vwap: [44, 44, 43, 43, 43, 43, 42, 42],
    ema200: [48, 48, 48, 47, 47, 47, 47, 47],
    why: 'FLAT. Price is sandwiched between the 9/20 below and VWAP/200 above — walls everywhere, no room to run. This is a chop tell, and it also fails the Runway Rule: no wall (VWAP or the 200) may sit between the entry and the first scale-out target. Walls overhead = no runway = no trade.',
  },
  {
    id: 's22',
    expected: 'LONG',
    trap: false,
    title: 'D4 · The Reclaim Sequence completes',
    ctx: 'Decisive close above VWAP + 200 · held from above · first bull flag riding the 20',
    ctxColor: 'emerald',
    candle: 'engulfing',
    values: [28, 24, 31, 47, 54, 50, 48, 52, 49, 57],
    ema20: [30, 29, 30, 34, 38, 41, 43, 44, 45, 47],
    vwap: [40, 40, 40, 41, 41, 41, 42, 42, 42, 43],
    ema200: [45, 45, 45, 45, 45, 45, 45, 45, 46, 46],
    triggerY: 52,
    dip1Idx: 6,
    dip2Idx: 8,
    entryIdx: 9,
    stopY: 44,
    why: 'GO LONG on the 2-min close through the flag trendline. This is the Reclaim Sequence completing: 1) a decisive close above BOTH VWAP and the 200, 2) the pullback HELD them from above, 3) the FIRST flag after the held reclaim — often the best trade of the move. The Gatekeeper is open: above VWAP, above the 9, above the 20 with the 20 rising, above the 200, runway clear.',
  },
  {
    id: 's23',
    expected: 'SHORT',
    trap: false,
    title: 'D5 · Fully stacked short',
    ctx: '15 & 5: LH/LL · 2-min below all four lines · 20 falling',
    ctxColor: 'coral',
    candle: 'bearish engulfing',
    values: [78, 64, 48, 56, 47, 53, 41, 32],
    ema9: [82, 71, 59, 58, 53, 54, 48, 41],
    ema20: [86, 78, 70, 65, 61, 59, 56, 52],
    vwap: [84, 80, 76, 73, 71, 69, 67, 65],
    ema200: [92, 91, 91, 90, 90, 89, 89, 88],
    triggerY: 47,
    dip1Idx: 3,
    dip2Idx: 5,
    entryIdx: 6,
    stopY: 60,
    stopLabel: 'Stop (above bounce swing high)',
    why: 'GO SHORT on the trigger. The short gate is fully open: 15/5 lower highs and lower lows; the 2-min below VWAP, the 9, the 20 with the 20 falling, and the 200 — A+ stacked 9 below 20 below 200. The bear-flag bounce never CLOSED back above the 20 (touches are fine, closes kill it), and the runway below is clear. This is the mirror of the green-light long.',
  },
  {
    id: 's24',
    expected: 'SKIP',
    trap: true,
    title: 'D6 · Chop — braided EMAs, flat VWAP',
    ctx: '9/20 braided flat · price has crossed VWAP 4× in 30 minutes',
    ctxColor: 'muted',
    candle: 'small overlapping',
    values: [44, 50, 43, 49, 44, 51, 45, 49],
    ema9: [45, 47, 46, 47, 46, 47, 46, 47],
    ema20: [46, 46, 46, 47, 46, 47, 47, 47],
    vwap: [47, 47, 47, 47, 47, 47, 47, 47],
    ema200: [49, 49, 49, 49, 48, 48, 48, 48],
    why: 'FLAT. Two chop tells at once — the 9/20 braided flat together, and price crossing a flat VWAP repeatedly — and any ONE is enough to sit on your hands. No setups exist here in either direction. Chop manufactures fake flags and fake breaks all day; the Gatekeeper exists so you never pay tuition on them.',
  },
]
