// 18 scenarios for the "Trade or Skip" trainer.
// Each scenario: id, expected ('LONG'|'SHORT'|'SKIP'|'WAIT'), trap (boolean — was this a classic trap to avoid?),
// ctx (15-min context label), ctxColor, candle, values (y-array 0..100), trigger, dip1Idx, dip2Idx, entryIdx (optional),
// stopY (optional), why (teaching), title.

export const SCENARIOS = [
  {
    id: 's1',
    expected: 'LONG',
    trap: false,
    title: 'Textbook with-trend long',
    ctx: '15-min: higher highs & higher lows',
    ctxColor: 'emerald',
    candle: 'engulfing',
    values: [18, 34, 52, 43, 53, 46, 60, 72],
    triggerY: 53,
    dip1Idx: 3,
    dip2Idx: 5,
    entryIdx: 6,
    stopY: 37,
    why: 'Textbook with-trend bull flag. Dip 1 → failed rally (the neckline is heads-up only, NOT the entry) → higher-low Dip 2 (the W is complete — heads-up only). The TRIGGER is the FIRST 2-min candle that CLOSES above the descending 2-min trendline. Take it. Stop: tentative 4-6 ticks beyond the broken trendline, final at the structure (the swing low at the bottom of the flag / lower low of the W).',
  },
  {
    id: 's2',
    expected: 'SHORT',
    trap: false,
    title: 'Mirror — with-trend short',
    ctx: '15-min: lower highs & lower lows',
    ctxColor: 'coral',
    candle: 'bearish engulfing',
    values: [82, 66, 48, 57, 47, 54, 40, 28],
    triggerY: 47,
    dip1Idx: 3,
    dip2Idx: 5,
    entryIdx: 6,
    stopY: 63,
    stopLabel: 'Stop (above rally high)',
    why: 'With-trend BEAR FLAG. 15-min must be in downtrend (lower highs and lower lows — MANDATORY for shorts). High 1 → failed dip back (the neckline is heads-up only) → lower-high High 2 (the M is complete — heads-up only). TRIGGER: FIRST 2-min candle that CLOSES BELOW the ascending 2-min trendline (the line connecting the higher lows of the rising flag). Stop: tentative 4-6 ticks above the broken trendline, final at the structure (swing high at the top of the bounce / higher high of the M). Bear flags work fast — time stop is 2 candles (4 minutes), not 3.',
  },
  {
    id: 's3',
    expected: 'SKIP',
    trap: true,
    title: 'Double-bottom AGAINST a downtrend',
    ctx: '15-min: DOWNTREND (lower highs & lower lows)',
    ctxColor: 'coral',
    candle: 'doji',
    values: [70, 55, 42, 40, 44, 41, 50, 58],
    triggerY: 44,
    dip1Idx: 3,
    dip2Idx: 5,
    why: 'This is a double-bottom forming AGAINST a downtrend — the old trap. The candle may look beautiful but the context is wrong. No bottom-picking. Sit out.',
  },
  {
    id: 's4',
    expected: 'SKIP',
    trap: true,
    title: 'Sideways tape',
    ctx: '15-min: sideways / choppy, no clear trend',
    ctxColor: 'muted',
    candle: 'mixed',
    values: [50, 44, 55, 46, 54, 45, 53, 47],
    why: 'No trend, no permission. The 15-min gate is closed. Sitting out IS the trade.',
  },
  {
    id: 's5',
    expected: 'WAIT',
    trap: false,
    title: 'Only the failed first rally so far',
    ctx: '15-min: higher highs & higher lows',
    ctxColor: 'emerald',
    candle: 'forming',
    values: [20, 38, 55, 45, 55, 50, 52, 53],
    triggerY: 55,
    dip1Idx: 3,
    why: 'The first rally up from Dip 1 has failed. The neckline is a heads-up signal, not the entry. Dip 2 hasn\'t printed yet, and no 2-min candle has closed above the descending TRENDLINE — which is the only trigger. Wait. There is no entry until the 2-min candle CLOSES above the trendline. Patience IS the edge.',
  },
  {
    id: 's6',
    expected: 'SKIP',
    trap: true,
    title: 'Unhealthy knife pullback',
    ctx: '15-min: higher highs & higher lows',
    ctxColor: 'emerald',
    candle: 'doji',
    values: [30, 48, 60, 40, 30, 25, 28, 33],
    ema20: [28, 35, 44, 46, 44, 40, 36, 34],
    why: 'The pullback knifed well below the 20 EMA and stayed there. Healthy pullbacks don\'t cave like this. Character has changed. Skip.',
  },
  {
    id: 's7',
    expected: 'SKIP',
    trap: true,
    title: 'Lower high on the 15-min',
    ctx: '15-min: just printed a LOWER HIGH',
    ctxColor: 'coral',
    candle: 'engulfing',
    values: [40, 55, 68, 60, 52, 57, 49, 46],
    triggerY: 57,
    dip1Idx: 4,
    dip2Idx: 5,
    why: 'The 15-min uptrend is now in question — the hard gate fails. Even with a "perfect" 2-min picture, no long.',
  },
  {
    id: 's8',
    expected: 'SKIP',
    trap: false,
    title: 'No candle confirmation',
    ctx: '15-min: higher highs & higher lows',
    ctxColor: 'emerald',
    candle: 'weak doji',
    values: [22, 36, 52, 44, 52, 46, 55, 61],
    triggerY: 52,
    dip1Idx: 3,
    dip2Idx: 5,
    entryIdx: 6,
    stopY: 38,
    why: 'Valid structure, but no confirmation candle at Dip 2 — just a weak doji. Lowest conviction. Smaller size or skip. Best practice: skip until the candle agrees.',
  },

  // ─── Phase 8 additions ─────────────────────────────────────────────
  {
    id: 's9',
    expected: 'LONG',
    trap: false,
    title: 'Clean with-trend second entry',
    ctx: '15-min: higher highs & higher lows',
    ctxColor: 'emerald',
    candle: 'engulfing',
    values: [25, 40, 58, 48, 58, 50, 63, 74],
    triggerY: 58,
    dip1Idx: 3,
    dip2Idx: 5,
    entryIdx: 6,
    stopY: 42,
    why: 'Clean with-trend bull flag. Dip 1 → failed rally (neckline is heads-up, not entry) → higher-low Dip 2 (W complete — heads-up only) → FIRST close above the descending 2-min trendline. Take it.',
  },
  {
    id: 's10',
    expected: 'SKIP',
    trap: true,
    title: 'Climactic 5th push + deep pullback',
    ctx: '15-min HH/HL but 5th extended push, climactic',
    ctxColor: 'gold',
    candle: 'climactic',
    values: [40, 55, 72, 60, 78, 55, 70, 52],
    why: 'A blow-off bar followed by a deep pullback is exhaustion. The trend may be ending. Stop taking new longs.',
  },
  {
    id: 's11',
    expected: 'SHORT',
    trap: false,
    title: 'With-trend short — second push',
    ctx: '15-min: lower highs & lower lows',
    ctxColor: 'coral',
    candle: 'bearish engulfing',
    values: [78, 62, 45, 55, 45, 52, 38, 27],
    triggerY: 45,
    dip1Idx: 3,
    dip2Idx: 5,
    entryIdx: 6,
    stopY: 60,
    stopLabel: 'Stop (above rally high)',
    why: 'Bear flag — exact mirror. 15-min downtrend (mandatory). Failed dip back (neckline = heads-up only) → lower-high High 2 (M complete — heads-up only) → FIRST close BELOW the ascending 2-min trendline (the line through the higher lows of the rising flag). Stop: tentative 4-6 ticks above the broken trendline, final at structure (top of bounce / higher high of the M). Time stop: 2 candles.',
  },
  {
    id: 's12',
    expected: 'SKIP',
    trap: true,
    title: '5-min broke its prior swing low',
    ctx: '15-min HH/HL, but the 5-min broke its prior swing low',
    ctxColor: 'coral',
    candle: 'doji',
    values: [30, 46, 60, 44, 30, 33, 29, 35],
    why: 'The 5-min health failed — the pullback broke the prior swing low. The "WHERE" gate is closed. Stand aside.',
  },
  {
    id: 's13',
    expected: 'WAIT',
    trap: false,
    title: 'No 2-min CLOSE yet',
    ctx: '15-min: higher highs & higher lows',
    ctxColor: 'emerald',
    candle: 'forming',
    values: [22, 38, 55, 45, 55, 47, 52, 52],
    triggerY: 55,
    dip1Idx: 3,
    dip2Idx: 5,
    why: 'Structure is right and the W is complete (heads-up), but the 2-min hasn\'t printed the FIRST close above the descending TRENDLINE yet. Neckline = heads-up. Trendline close = trigger. Wait. The trendline close is the contract.',
  },
  {
    id: 's14',
    expected: 'SKIP',
    trap: true,
    title: 'Double top in an UPTREND',
    ctx: '15-min: higher highs & higher lows',
    ctxColor: 'emerald',
    candle: 'rejection',
    values: [40, 58, 72, 64, 72, 66, 60, 55],
    why: 'A "double top" tempting a short — but the trend is UP. With-trend only. Never short this.',
  },
  {
    id: 's15',
    expected: 'LONG',
    trap: false,
    title: 'Strong trend, shallow pullback',
    ctx: '15-min: strong HH/HL',
    ctxColor: 'emerald',
    candle: 'engulfing',
    values: [30, 48, 62, 57, 63, 58, 68, 78],
    ema20: [28, 36, 46, 50, 52, 54, 60, 66],
    triggerY: 63,
    dip1Idx: 3,
    dip2Idx: 5,
    entryIdx: 6,
    stopY: 53,
    why: 'Strong trend, shallow pullback to the 9 EMA — the textbook A+ second entry. Take it.',
  },
  {
    id: 's16',
    expected: 'SKIP',
    trap: true,
    title: 'Sideways range',
    ctx: '15-min: sideways range, no trend',
    ctxColor: 'muted',
    candle: 'doji',
    values: [48, 42, 54, 43, 53, 44, 53, 45],
    why: 'Clean bounces, but no trend. We don\'t trade ranges. Sit out.',
  },
  {
    id: 's17',
    expected: 'LONG',
    trap: false,
    title: 'Morning star at Dip 2 (Strong, not A+)',
    ctx: '15-min: higher highs & higher lows',
    ctxColor: 'emerald',
    candle: 'morning star',
    values: [24, 40, 56, 46, 56, 48, 60, 70],
    triggerY: 56,
    dip1Idx: 3,
    dip2Idx: 5,
    entryIdx: 6,
    stopY: 41,
    why: 'Valid with-trend second entry confirmed by a morning star — a Strong (not A+) candle. Rare when you get it. Take it.',
  },
  {
    id: 's18',
    expected: 'SKIP',
    trap: true,
    title: 'Don\'t chase — no pullback',
    ctx: '15-min HH/HL, but price far above the 20 EMA with no pullback',
    ctxColor: 'emerald',
    candle: 'thrust',
    values: [20, 35, 52, 66, 78, 84, 80, 86],
    ema20: [18, 24, 32, 42, 52, 60, 64, 68],
    why: 'Nothing to buy. Don\'t chase. Wait for a pullback.',
  },
]
